artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  kaggle_dataset: "palashfendarkar/wa-fnusec-telcocustomerchurn"
  file: "WA_Fn-UseC_-Telco-Customer-Churn.csv"
  local_data_file: "artifacts/data_ingestion/WA_Fn-UseC_-Telco-Customer-Churn.csv"
  data_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  local_data_file: "artifacts/data_ingestion/WA_Fn-UseC_-Telco-Customer-Churn.csv"
  status_file: "artifacts/data_validation/data_validation_status.txt"
  status_message_file: "artifacts/data_validation/data_validation_status_message.txt"

data_transformation:
  root_dir: artifacts/data_transformation
  local_data_file: artifacts/data_ingestion/WA_Fn-UseC_-Telco-Customer-Churn.csv
  filtered_data_file: artifacts/data_transformation/customer_churn_data.csv
  encoded_data_file: artifacts/data_transformation/customer_churn_data.csv
  encoder_file: artifacts/data_transformation/encoders.pkl

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json

model_prediction:
  root_dir: artifacts/model_prediction
  status_file: artifacts/model_prediction/data_validation_status.txt
  model_path: artifacts/model_trainer/model.joblib

mlflow:
  experiment_name: "Customer Churn Model Training"
  tracking_uri_base: "https://dagshub.com/jatintomer12/customer_churn_prediction.mlflow"
