artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  kaggle_dataset: "palashfendarkar/wa-fnusec-telcocustomerchurn"
  file: "WA_Fn-UseC_-Telco-Customer-Churn.csv"
  local_data_file: "artifacts/data_ingestion/WA_Fn-UseC_-Telco-Customer-Churn.csv"
  data_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  local_data_file: "artifacts/data_ingestion/WA_Fn-UseC_-Telco-Customer-Churn.csv"
  status_file: "artifacts/data_validation/data_validation_status.txt"
  status_message_file: "artifacts/data_validation/data_validation_status_message.txt"
